# Generated by Django 4.1.3 on 2023-05-06 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=60)),
                ('name_jamo', models.CharField(db_index=True, max_length=60)),
                ('content', models.TextField(max_length=300)),
                ('barcode', models.CharField(max_length=13)),
                ('expire', models.DateField()),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
